export default{
    theme: {
        extend:{
            colors: {
                'text': {
                    50: 'oklab(var(--text-50))',
                    100: 'oklab(var(--text-100))',
                    200: 'oklab(var(--text-200))',
                    300: 'oklab(var(--text-300))',
                    400: 'oklab(var(--text-400))',
                    500: 'oklab(var(--text-500))',
                    600: 'oklab(var(--text-600))',
                    700: 'oklab(var(--text-700))',
                    800: 'oklab(var(--text-800))',
                    900: 'oklab(var(--text-900))',
                    950: 'oklab(var(--text-950))',
                },
                'background': {
                    50: 'oklab(var(--background-50))',
                    100: 'oklab(var(--background-100))',
                    200: 'oklab(var(--background-200))',
                    300: 'oklab(var(--background-300))',
                    400: 'oklab(var(--background-400))',
                    500: 'oklab(var(--background-500))',
                    600: 'oklab(var(--background-600))',
                    700: 'oklab(var(--background-700))',
                    800: 'oklab(var(--background-800))',
                    900: 'oklab(var(--background-900))',
                    950: 'oklab(var(--background-950))',
                },
                'primary': {
                    50: 'oklab(var(--primary-50))',
                    100: 'oklab(var(--primary-100))',
                    200: 'oklab(var(--primary-200))',
                    300: 'oklab(var(--primary-300))',
                    400: 'oklab(var(--primary-400))',
                    500: 'oklab(var(--primary-500))',
                    600: 'oklab(var(--primary-600))',
                    700: 'oklab(var(--primary-700))',
                    800: 'oklab(var(--primary-800))',
                    900: 'oklab(var(--primary-900))',
                    950: 'oklab(var(--primary-950))',
                },
                'secondary': {
                    50: 'oklab(var(--secondary-50))',
                    100: 'oklab(var(--secondary-100))',
                    200: 'oklab(var(--secondary-200))',
                    300: 'oklab(var(--secondary-300))',
                    400: 'oklab(var(--secondary-400))',
                    500: 'oklab(var(--secondary-500))',
                    600: 'oklab(var(--secondary-600))',
                    700: 'oklab(var(--secondary-700))',
                    800: 'oklab(var(--secondary-800))',
                    900: 'oklab(var(--secondary-900))',
                    950: 'oklab(var(--secondary-950))',
                },
                'accent': {
                    50: 'oklab(var(--accent-50))',
                    100: 'oklab(var(--accent-100))',
                    200: 'oklab(var(--accent-200))',
                    300: 'oklab(var(--accent-300))',
                    400: 'oklab(var(--accent-400))',
                    500: 'oklab(var(--accent-500))',
                    600: 'oklab(var(--accent-600))',
                    700: 'oklab(var(--accent-700))',
                    800: 'oklab(var(--accent-800))',
                    900: 'oklab(var(--accent-900))',
                    950: 'oklab(var(--accent-950))',
                },
            },
        }
    }
}